version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bibliotheque-postgres
    environment:
      POSTGRES_DB: bibliotheque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: bibliotheque-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: