spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Mail (mock par @MockBean mais Spring a besoin des propriétés pour démarrer)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test
