# Exemple de cours
# workflow de documentation
#workflow secondaire destiné à être inclus dans un workflow principal
name: Documentation
on:
  push:
    branches:
      - main

  workflow_call:

jobs:
