name: DAST

on:
  workflow_dispatch:
    inputs:
      app_url:
        required: true
        default: "http://localhost:8080"

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ZAP scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ github.event.inputs.app_url }}
          fail_action: false
