name: Documentation

on:
  workflow_call:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Zensical
        run: pip install zensical

      - name: Deploy to GitHub Pages
        run: zensical gh-deploy --force
